[build-system]
requires = ["setuptools", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["tests"]

[tool.black]
extend-exclude = "openldap/"
