from typing import Iterable, Tuple


def get_lmdb_version() -> str: ...

class LmdbDatabase:
    def __init__(self, db_name: str, no_subdir: bool = False, read_only: bool = False): ...
    def put(self, key: bytes, value: bytes) -> None: ...
    def get(self, key: bytes) -> bytes: ...
    def delete(self, key: bytes) -> None: ...
    def put_batch(self, items: Iterable[Tuple[bytes, bytes]]) -> None: ...
    def get_batch(self, keys: Iterable[bytes]) -> Tuple[bytes]: ...
