name: Build and Test
on: [push]
jobs:
  # build:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #       python-version: ["3.7", "3.8", "3.9", "3.10"]
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #     - uses: actions/setup-python@v3
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - run: |
  #         python -m pip install --upgrade pip setuptools wheel
  #         pip install Cython pytest
  #     - run: python setup.py build_ext --inplace
  #     - run: pytest -v

  build_wheels:
    runs-on: ${{ matrix.os }}
    # needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v3
      - run: python -m pip install cibuildwheel
      - run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_SKIP: cp36-*
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest -v {project}/tests
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
