name: Build wheels
on:
  release:
    types: [published]
jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      # use clang in macos
      - name: Set environment variables for macOS
        if: matrix.os == 'macos-latest'
        run: |
          echo "CC=/usr/bin/clang" >> $GITHUB_ENV
          echo "CXX=/usr/bin/clang++" >> $GITHUB_ENV

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1

          # skip Python 3.6 and PyPy
          CIBW_SKIP: cp36-* pp*

          # build macos arm64 and testing for it
          CIBW_ARCHS_MACOS: x86_64 universal2 arm64
          CIBW_TEST_SKIP: "*-macosx_arm64 *-macosx_universal2:arm64"

          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest -v {project}/tests
        
      - name: Save wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
